server:
  port : 9999
zuul:
  routes:
    offer:
      path: /offer/**
      url: http://52.201.218.99:1001/api/v1
    shoe:
      path: /shoe/**
      url: http://52.201.218.99:1002/api/v1
    wishlist:
      path: /wishlist/**
      url: http://52.201.218.99:1003
    cart:
      path: /cart/**
      url: http://52.201.218.99:1004/api/v1
